### ISSUE TITLE
Improve error message when requesting empty time period

### ISSUE THREAD

**Issue by EHJ-52n** [52North/SOS#167]
The current error message when requesting an empty time period because of start == end is a bit confusing:
```
ITime Time period: 2014-09-26T22:00:01.000Z, null, 2014-09-26T22:00:01.000Z, null is not supported
```
It should be improved to something like: 
```
Bad request: Empty time period found in request.
Possible cases: start == end or start > end.
Start: 2014-09-26T22:00:01.000Z, null
End: 2014-09-26T22:00:01.000Z, null
```

The according exception stack trace:
```
2015-01-29 11:32:28,125 DEBUG [http-bio-8080-exec-54] [CodingRepository.java:148] Requested ambiguous Decoder implementations for XmlNamespaceDecoderKey[namespace=http://www.opengis.net/sos/2.0, type=GetObservationDocumentImpl]: Found org.n52.sos.gda.GetDataAvailabilityXmlDecoder@54182e18, org.n52.sos.decode.SosDecoderv20@6d721560; Choosing org.n52.sos.decode.SosDecoderv20@6d721560.
2015-01-29 11:32:28,125 DEBUG [http-bio-8080-exec-54] [SosDecoderv20.java:159] REQUESTTYPE:class net.opengis.sos.x20.impl.GetObservationDocumentImpl
2015-01-29 11:32:28,130 DEBUG [http-bio-8080-exec-54] [SosEventBus.java:166] No Listeners for SosEvent RequestEvent[request=org.n52.sos.request.GetObservationRequest[service=SOS, version=2.0.0, operation=GetObservation]]
2015-01-29 11:32:28,131 DEBUG [http-bio-8080-exec-54] [SosEventBus.java:151] Queueing Event ExceptionEvent[exception=UnsupportedTimeException] for Listener org.n52.sos.service.ExceptionLogger@703653d9
2015-01-29 11:32:28,131 DEBUG [http-bio-8080-exec-54] [SosEventBus.java:258] Submitting Event ExceptionEvent[exception=UnsupportedTimeException] to Listener org.n52.sos.service.ExceptionLogger@703653d9
2015-01-29 11:32:28,132 DEBUG [http-bio-8080-exec-54] [ExceptionLogger.java:83] Exception thrown
org.n52.sos.exception.ows.concrete.UnsupportedTimeException: ITime Time period: 2014-09-26T22:00:01.000Z, null, 2014-09-26T22:00:01.000Z, null is not supported
	at org.n52.sos.ds.hibernate.util.TemporalRestriction.get(TemporalRestriction.java:88) ~[hibernate-common-4.3.0-M4.jar:na]
	at org.n52.sos.ds.hibernate.util.TemporalRestrictions.filter(TemporalRestrictions.java:982) ~[hibernate-common-4.3.0-M4.jar:na]
	at org.n52.sos.ds.hibernate.util.TemporalRestrictions.during(TemporalRestrictions.java:557) ~[hibernate-common-4.3.0-M4.jar:na]
	at org.n52.sos.ds.hibernate.util.TemporalRestrictions.filter(TemporalRestrictions.java:1021) ~[hibernate-common-4.3.0-M4.jar:na]
	at org.n52.sos.ds.hibernate.util.TemporalRestrictions.getDisjunction(TemporalRestrictions.java:1095) ~[hibernate-common-4.3.0-M4.jar:na]
	at org.n52.sos.ds.hibernate.util.TemporalRestrictions.filter(TemporalRestrictions.java:1060) ~[hibernate-common-4.3.0-M4.jar:na]
	at org.n52.sos.ds.hibernate.util.HibernateGetObservationHelper.getTemporalFilterCriterion(HibernateGetObservationHelper.java:363) ~[hibernate-dao-4.3.0-M4.jar:na]
	at org.n52.sos.ds.hibernate.GetObservationDAO.querySeriesObservationForStreaming(GetObservationDAO.java:453) ~[hibernate-dao-4.3.0-M4.jar:na]
	at org.n52.sos.ds.hibernate.GetObservationDAO.getObservation(GetObservationDAO.java:135) ~[hibernate-dao-4.3.0-M4.jar:na]
	at org.n52.sos.request.operator.SosGetObservationOperatorV20.receive(SosGetObservationOperatorV20.java:90) ~[core-v20-4.3.0-M4.jar:na]
	at org.n52.sos.request.operator.SosGetObservationOperatorV20.receive(SosGetObservationOperatorV20.java:67) ~[core-v20-4.3.0-M4.jar:na]
	at org.n52.sos.request.operator.AbstractRequestOperator.receiveRequest(AbstractRequestOperator.java:156) ~[api-4.3.0-M4.jar:na]
	at org.n52.sos.service.operator.AbstractServiceOperator.receiveRequest(AbstractServiceOperator.java:61) ~[api-4.3.0-M4.jar:na]
	at org.n52.sos.binding.PoxBinding.doPostOperation(PoxBinding.java:73) ~[binding-pox-4.3.0-M4.jar:na]
	at org.n52.sos.service.SosService.doPost(SosService.java:140) [api-4.3.0-M4.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api-3.0.jar:na]
[...]
```

**Comment by CarstenHollmann** [comment]
Fixed in https://github.com/52North/SOS/pull/170
