### ISSUE TITLE
SQL-Server 2012 Express: Can not clean datasource via admin/datasource -> clear datasource

### ISSUE THREAD

**Issue by EHJ-52n** [52North/SOS#258]
The datasource of the SOS cannot be cleared!

Exception log:
```
06-Jul-2015 13:12:56.079 SEVERE [http-apr-8080-exec-3] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [dispatcher] in context with path [/52n-sos-webapp##4.3.0-SNAPSHOT] threw exception [Request processing failed; nested exception is java.lang.NullPointerException: Name is null] with root cause
 java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Unknown Source)
	at org.n52.sos.ds.HibernateDatasourceConstants$DatabaseConcept.valueOf(HibernateDatasourceConstants.java:81)
	at org.n52.sos.ds.datasource.AbstractHibernateDatasource.getDatabaseConceptMappingDirectory(AbstractHibernateDatasource.java:384)
	at org.n52.sos.ds.datasource.AbstractHibernateDatasource.getConfig(AbstractHibernateDatasource.java:360)
	at org.n52.sos.ds.datasource.AbstractSqlServerDatasource.clear(AbstractSqlServerDatasource.java:256)
	at org.n52.sos.web.admin.AdminDatasourceController.clearDatasource(AdminDatasourceController.java:126)
[...]
```

SOS metadata:
- Version: 4.3.0-SNAPSHOT
- Branch: distribution/*****
- Revision: 31531e28fc7ed7e18843a41514bfa73e4368693b
- Build date: 2015-04-20 12:50:59+0200
- Installation date: 2015-04-20 12:50:59+0200

**Comment by EHJ-52n** [comment]
Not reproducible atm. Waiting for additional information from client.

**Comment by EHJ-52n** [comment]
The problem occurred because of missing property in datasource.properties.

Details can be found in 6bb0a5a6e7.
