### ISSUE TITLE
StackOverflowError in DescribeSensor operation when inserted with relatedFeature

### ISSUE THREAD

**Issue by jruizaranguren** [52North/SOS#320]
I'm getting a StackOverflowError when issuing a DescribeSensor call for a procedure that has been inserted with a relatedFeature (develop branch). This is the insertSensor json request:

```json
{
    "featureOfInterestType" : ["http://www.opengis.net/def/samplingFeatureType/OGC-OM/2.0/SF_SamplingPoint"],
    "observableProperty" : ["http://sweet.jpl.nasa.gov/2.3/matrElementalMolecule.owl#Cl2"],
    "observationType" : ["http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement"],
    "procedureDescription" : "...",
    "procedureDescriptionFormat" : "http://www.opengis.net/sensorml/2.0",
    "relatedFeature" : [{
            "role" : "http://www.opengis.net/def/samplingFeatureType/OGC-OM/2.0/SF_SamplingPoint",
            "target" : "http://idena.navarra.es/olk/ad1"
        }
    ],
    "request" : "InsertSensor",
    "service" : "SOS",
    "version" : "2.0.0"
}
```

```xml
<sml:PhysicalComponent 
    xmlns:gml="http://www.opengis.net/gml/3.2" 
    xmlns:swe="http://www.opengis.net/swe/2.0" 
    xmlns:xlink="http://www.w3.org/1999/xlink" 
    xmlns:gco="http://www.isotc211.org/2005/gco" 
    xmlns:gmd="http://www.isotc211.org/2005/gmd" 
    xmlns:sml="http://www.opengis.net/sensorml/2.0" 
    xmlns:swes="http://www.opengis.net/swes/2.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="xmlns"
    gml:id="physicalcomponent_2f55d9f0-5ac9-11e5-985c-002481c64436" 
    xsi:schemaLocation="http://www.opengis.net/swes/2.0 http://schemas.opengis.net/swes/2.0/swesDescribeSensor.xsd http://www.isotc211.org/2005/gco http://schemas.opengis.net/iso/19139/20070417/gco/gco.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd http://www.opengis.net/sensorml/2.0 http://schemas.opengis.net/sensorML/2.0/sensorML.xsd">
    <gml:identifier codeSpace="uniqueID">http://idena.navarra.es/olk/ad1/cl01</gml:identifier>
    <sml:keywords>
        <sml:KeywordList>
            <sml:keyword>http://idena.navarra.es/olk/ad1/cl01</sml:keyword>
            <sml:keyword>chlorinemeter cl01 del ad1 localizado en olk</sml:keyword>
            <sml:keyword>olk_ad1_cl01</sml:keyword>
        </sml:KeywordList>
    </sml:keywords>
    <sml:identification>
        <sml:IdentifierList>
            <sml:identifier>
                <sml:Term definition="urn:ogc:def:identifier:OGC:1.0:uniqueID">
                    <sml:label>uniqueID</sml:label>
                    <sml:value>http://idena.navarra.es/olk/ad1/cl01</sml:value>
                </sml:Term>
            </sml:identifier>
            <sml:identifier>
                <sml:Term definition="urn:ogc:def:identifier:OGC:1.0:longName">
                    <sml:label>longName</sml:label>
                    <sml:value>chlorinemeter cl01 del ad1 localizado en olk</sml:value>
                </sml:Term>
            </sml:identifier>
            <sml:identifier>
                <sml:Term definition="urn:ogc:def:identifier:OGC:1.0:shortName">
                    <sml:label>shortName</sml:label>
                    <sml:value>olk_ad1_cl01</sml:value>
                </sml:Term>
            </sml:identifier>
        </sml:IdentifierList>
    </sml:identification>
    <sml:validTime>
        <gml:TimePeriod gml:id="tp_2f55b2e1-5ac9-11e5-b6dd-002481c64436">
            <gml:beginPosition>2015-01-01T00:00:00</gml:beginPosition>
            <gml:endPosition indeterminatePosition="unknown"/>
        </gml:TimePeriod>
    </sml:validTime>
    <sml:capabilities name="offerings">
        <sml:CapabilityList>
            <sml:capability name="olkad1cl01_offering_1">
                <swe:Text definition="http://www.opengis.net/def/offering/identifier">
                    <swe:label>olkad1cl01_offering_1</swe:label>
                    <swe:value>http://idena.navarra.es/olk/ad1/cl01/offering/1</swe:value>
                </swe:Text>
            </sml:capability>
        </sml:CapabilityList>
    </sml:capabilities>
    <sml:featuresOfInterest>
        <sml:FeatureList definition="http://www.opengis.net/def/featureOfInterest/identifier">
            <swe:label>featuresOfInterest</swe:label>
            <sml:feature xlink:href="http://idena.navarra.es/olk/ad1"/>
        </sml:FeatureList>
    </sml:featuresOfInterest>
    <sml:inputs>
        <sml:InputList>
            <sml:input name="Chlorine">
                <sml:ObservableProperty definition="http://sweet.jpl.nasa.gov/2.3/matrElementalMolecule.owl#Cl2"/>
            </sml:input>
        </sml:InputList>
    </sml:inputs>
    <sml:outputs>
        <sml:OutputList>
            <sml:output name="Chlorine">
                <swe:Quantity definition="http://sweet.jpl.nasa.gov/2.3/matrElementalMolecule.owl#Cl2">
                    <swe:label>Chlorine</swe:label>
                    <swe:uom code="mg/L"/>
                </swe:Quantity>
            </sml:output>
        </sml:OutputList>
    </sml:outputs>
    <sml:position>
        <swe:Vector referenceFrame="urn:ogc:def:crs:EPSG::4326">
            <swe:coordinate name="easting">
                <swe:Quantity axisID="x">
                    <swe:uom code="degree"/>
                    <swe:value>42.843</swe:value>
                </swe:Quantity>
            </swe:coordinate>
            <swe:coordinate name="northing">
                <swe:Quantity axisID="y">
                    <swe:uom code="degree"/>
                    <swe:value>-1.5804</swe:value>
                </swe:Quantity>
            </swe:coordinate>
        </swe:Vector>
    </sml:position>
</sml:PhysicalComponent>
```

The error retrieved from catalina.out:

```
Exception in thread "http-bio-8080-exec-11" java.lang.StackOverflowError
        at org.postgresql.jdbc2.AbstractJdbc2Statement.<init>(AbstractJdbc2Statement.java:153)
        at org.postgresql.jdbc3.AbstractJdbc3Statement.<init>(AbstractJdbc3Statement.java:40)
        at org.postgresql.jdbc3g.AbstractJdbc3gStatement.<init>(AbstractJdbc3gStatement.java:27)
        at org.postgresql.jdbc4.AbstractJdbc4Statement.<init>(AbstractJdbc4Statement.java:33)
        at org.postgresql.jdbc4.Jdbc4Statement.<init>(Jdbc4Statement.java:28)
        at org.postgresql.jdbc4.Jdbc4PreparedStatement.<init>(Jdbc4PreparedStatement.java:21)
        at org.postgresql.jdbc4.Jdbc4PreparedStatement.<init>(Jdbc4PreparedStatement.java:16)
        at org.postgresql.jdbc4.Jdbc4Connection.prepareStatement(Jdbc4Connection.java:39)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.prepareStatement(AbstractJdbc3Connection.java:276)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.prepareStatement(AbstractJdbc2Connection.java:311)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:213)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:162)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1885)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1862)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839)
        at org.hibernate.loader.Loader.doQuery(Loader.java:910)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
        at org.hibernate.loader.Loader.doList(Loader.java:2554)
        at org.hibernate.loader.Loader.doList(Loader.java:2540)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
        at org.hibernate.loader.Loader.list(Loader.java:2365)
        at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:126)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1718)
        at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:380)
        at org.n52.sos.ds.hibernate.dao.observation.series.AbstractSeriesObservationDAO.getSamplingGeometries(AbstractSeriesObservationDAO.java:189)
        at org.n52.sos.ds.hibernate.HibernateFeatureQueryHandler.getGeomtery(HibernateFeatureQueryHandler.java:556)
        at org.n52.sos.ds.hibernate.HibernateFeatureQueryHandler.createSosAbstractFeature(HibernateFeatureQueryHandler.java:412)
        at org.n52.sos.ds.hibernate.HibernateFeatureQueryHandler.createSosAbstractFeature(HibernateFeatureQueryHandler.java:423)
previous line is repeated a couple of times...
```

Looking at the code it seems it is a problem with a never-ending recursion, but I'm not sure if it is a mistake in my insertSensor request or a bug in the code:

```java
        if (feature instanceof TFeatureOfInterest) {
            final Set<FeatureOfInterest> parentFeatures = ((TFeatureOfInterest) feature).getParents();
            if (parentFeatures != null && !parentFeatures.isEmpty()) {
                final List<AbstractFeature> sampledFeatures = new ArrayList<AbstractFeature>(parentFeatures.size());
                for (final FeatureOfInterest parentFeature : parentFeatures) {
                    sampledFeatures.add(createSosAbstractFeature(parentFeature, queryObject, session));
                }
                sampFeat.setSampledFeatures(sampledFeatures);
            }
        }
```

> Edit: it seems to be related to JSON binding. I have inserted the same sensor with POX binding and swes:relatedFeature and it works nicely.

**Comment by CarstenHollmann** [comment]
Did you insert observations after the insertion of the senor with the JSON binding? And with the POX binding you only inserted the sensor?
Because the problem is the InsertObservation because here the featureOfInterest is inserted into the database. Your defined reladedFeature is the same as the samplingFeature/featureOfInterest and the SOS creates a parent/child relationship between reladedFeature and samplingFeature/featureOfInterest without checking id parent/child are the same.
This results in a loop when the featureOfInterest is queried from the database.
I will label this as a bug.

**Comment by jruizaranguren** [comment]
Yes, exactly. I realised yesterday that the problem arised when using InsertObservation. Thanks.
