### ISSUE TITLE
After some use of the service I get a NullPointerException when sending DescribeSensor

### ISSUE THREAD

**Issue by jruizaranguren** [52North/SOS#343]
We have a couple of sensors and observations that we are using to test the service. It works nicely after we have inserted the data, but after a while (we have not modified any data) when we request a DescribeSensor it returns a 200 OK response with an empty object.

I doubt that the concrete example has nothing to do with the error because it is working properly after insertion.

We can see in the log that it is throwing a NullPointerException:

```
oct 27, 2015 11:51:31 AM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() para servlet SOS lanzó excepción
java.lang.NullPointerException
        at org.n52.sos.ogc.sensorML.elements.SmlCapabilities.getCapabilities(SmlCapabilities.java:86)
        at org.n52.sos.encode.SensorMLEncoderv20.createCapability(SensorMLEncoderv20.java:954)
        at org.n52.sos.encode.SensorMLEncoderv20.addDescribedObjectValues(SensorMLEncoderv20.java:578)
        at org.n52.sos.encode.SensorMLEncoderv20.addPhysicalComponentValues(SensorMLEncoderv20.java:497)
        at org.n52.sos.encode.SensorMLEncoderv20.addValuesToXmlObject(SensorMLEncoderv20.java:377)
        at org.n52.sos.encode.SensorMLEncoderv20.encode(SensorMLEncoderv20.java:243)
        at org.n52.sos.encode.SensorMLEncoderv20.encode(SensorMLEncoderv20.java:170)
        at org.n52.sos.util.CodingHelper.encodeObjectToXml(CodingHelper.java:70)
        at org.n52.sos.util.CodingHelper.encodeObjectToXml(CodingHelper.java:83)
        at org.n52.sos.encode.json.impl.DescribeSensorResponseEncoder.toString(DescribeSensorResponseEncoder.java:73)
        at org.n52.sos.encode.json.impl.DescribeSensorResponseEncoder.encodeDescription(DescribeSensorResponseEncoder.java:77)
        at org.n52.sos.encode.json.impl.DescribeSensorResponseEncoder.encodeDescriptions(DescribeSensorResponseEncoder.java:90)
        at org.n52.sos.encode.json.impl.DescribeSensorResponseEncoder.encodeResponse(DescribeSensorResponseEncoder.java:63)
        at org.n52.sos.encode.json.impl.DescribeSensorResponseEncoder.encodeResponse(DescribeSensorResponseEncoder.java:55)
        at org.n52.sos.encode.json.AbstractSosResponseEncoder.encodeJSON(AbstractSosResponseEncoder.java:66)
        at org.n52.sos.encode.json.AbstractSosResponseEncoder.encodeJSON(AbstractSosResponseEncoder.java:50)
        at org.n52.sos.encode.json.JSONEncoder.encode(JSONEncoder.java:119)
        at org.n52.sos.encode.json.JSONEncoder.encode(JSONEncoder.java:66)
        at org.n52.sos.encode.AbstractServiceResponseWriter.write(AbstractServiceResponseWriter.java:66)
        at org.n52.sos.encode.AbstractServiceResponseWriter.write(AbstractServiceResponseWriter.java:51)
        at org.n52.sos.util.http.HTTPUtils$GenericWritable.write(HTTPUtils.java:229)
        at org.n52.sos.util.http.HTTPUtils.writeObject(HTTPUtils.java:173)
        at org.n52.sos.util.http.HTTPUtils.writeObject(HTTPUtils.java:132)
        at org.n52.sos.binding.SimpleBinding.writeResponse(SimpleBinding.java:280)
        at org.n52.sos.binding.JSONBinding.doPostOperation(JSONBinding.java:107)
        at org.n52.sos.service.SosService.doPost(SosService.java:140)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
        at org.n52.sos.service.ConfiguratedHttpServlet.service(ConfiguratedHttpServlet.java:53)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:168)
        at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:233)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by dbciar** [comment]
I ran into this same issue around a hour or two ago, except that there are no errors in the logs - no NullPointerException.

The behaviour is as follows:
1. Insert sensor using the web client (SOS 2.0.0, POX) using a SensorML description wrapped in the SOS InsertSensor call that worked earlier, and also worked with DescribeSensor.
1.1 The SOS Server returns a successful InsertSensor reply, providing the procedure and observationoffering values.
2. Call DescribeSensor (SOS 2.0.0 POX) using the previously returned procedure value
2.1 Client returns a 200 OK result, but with no information in the reply.
2.2 Using KVP DescribeSensor call in the browser address bar returns an empty xml document error (XML Parsing Error: no element found)
3. Calling GetCapabilities shows the procedure and observationoffering

The sensor definitely was entered into the system earlier in the day (a clear datasource used between then and this insert), and definitely returned the sensor description when DescribeSensor was called, all with the same SOS and POX encoding values.

It first occurred when I was trying some sensor combinations, exploring the system.  I had added two separate PhysicalComponents, and then used their procedure ID's, and the KVP DescribeSensor calls as xlink:title and xlink:html attributes in a PhysicalSystem (to see if that would work), and when I tried a DescribeSensor I got the empty reply.  All three sensors were entered into the procedure table in the DB, and GetCapabilities showed all three procedures and observationofferings, but since that point no DescribeSensor has worked.

I restarted Tomcat, and then restarted the VM, cleared the browser cache and refreshed, but I still get the empty 200 OK return for DescribeSensor.

**Comment by dbciar** [comment]
Potentially related, is a situation where I found an empty result is being sent from the server to the requester when DescribeSensor is called, however there are no warnings or errors in the log.

I found that when I included the following capabilities in a sensor description:

https://gist.github.com/dbciar/2da400d72cf81b8717af

sent to the server in POX encoding, SOS 2.0.0, SML 2.0, the server returns a successful result, providing the procedure ID and the observationoffering values.  However, when the procedure ID is then used in a POX or KVP call to DescribeSensor, an empty result is returned.  Calling GetCapabilities shows the procedure to be in the server, and the entry can be found in the procedures DB table also.

This was found to occur using the 4.3.4 SOS bundle download, and can be demonstrated by adding the capabilities excerpt to the SOS server Client's 'InsertSensor' example for procedure 'http://www.52north.org/test/procedure/9'.

**Comment by CarstenHollmann** [comment]
@jruizaranguren 
Which SOS version do you use?
Do you inserted a SensorML 1.0.1 or a SensorML 2.0 encoded sensor description?
Does this error occurs at different or always at the same procedure?
What was the requested procedureDescriptionFormat when the error occurs?

It is helpful to provide the procedure description files to replicate the problem.

**Comment by CarstenHollmann** [comment]
@dbciar I have checked the sensor description with the current dev version (4.4.0-SNAPSHOT) and there an exception is thrown that the `QuantityRange` is not supported as a field element of the `DataRecord` (that also applies to version 4.3.4).

**Comment by jruizaranguren** [comment]
@CarstenHollmann 
- SOS version: 4.4.0-SNAPSHOT commit: 'a0d7ae3f06f8a34b843e7133e099542c7035cc2e' @ 2015-09-18 11:40:55+0200.
- Sensor description: SensorML 2.0.
- It occurs with any procedure once it starts happening.

Procedure description sample (all are similar changing just observable property):

```xml
<sml:PhysicalComponent xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:swe="http://www.opengis.net/swe/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:sos="http://www.opengis.net/sos/2.0" xmlns:sml="http://www.opengis.net/sensorml/2.0" xmlns:swes="http://www.opengis.net/swes/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="xmlns" gml:id="physicalcomponent_91fa5c8f-7d5e-11e5-80ec-002481c64436" xsi:schemaLocation="http://www.opengis.net/swes/2.0 http://schemas.opengis.net/swes/2.0/swesDescribeSensor.xsd http://www.isotc211.org/2005/gco http://schemas.opengis.net/iso/19139/20070417/gco/gco.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd http://www.opengis.net/sensorml/2.0 http://schemas.opengis.net/sensorML/2.0/sensorML.xsd">
	<gml:identifier codeSpace="uniqueID">http://idena.navarra.es/olk/ad1/cl01</gml:identifier>
	<gml:name>chlorinemeter cl01 of ad1 in olk</gml:name>
	<sml:keywords>
		<sml:KeywordList>
			<sml:keyword>http://idena.navarra.es/olk/ad1/cl01</sml:keyword>
			<sml:keyword>chlorinemeter cl01 of ad1 in olk</sml:keyword>
			<sml:keyword>olk_ad1_cl01</sml:keyword>
		</sml:KeywordList>
	</sml:keywords>
	<sml:identification>
		<sml:IdentifierList>
			<sml:identifier>
				<sml:Term definition="urn:ogc:def:identifier:OGC:1.0:uniqueID">
					<sml:label>uniqueID</sml:label>
					<sml:value>http://idena.navarra.es/olk/ad1/cl01</sml:value>
				</sml:Term>
			</sml:identifier>
			<sml:identifier>
				<sml:Term definition="urn:ogc:def:identifier:OGC:1.0:longName">
					<sml:label>longName</sml:label>
					<sml:value>chlorinemeter cl01 of ad1 in olk</sml:value>
				</sml:Term>
			</sml:identifier>
			<sml:identifier>
				<sml:Term definition="urn:ogc:def:identifier:OGC:1.0:shortName">
					<sml:label>shortName</sml:label>
					<sml:value>olk_ad1_cl01</sml:value>
				</sml:Term>
			</sml:identifier>
		</sml:IdentifierList>
	</sml:identification>
	<sml:validTime>
		<gml:TimePeriod gml:id="tp_91fa0e70-7d5e-11e5-b7a1-002481c64436">
			<gml:beginPosition>2015-01-01T00:00:00</gml:beginPosition>
			<gml:endPosition indeterminatePosition="unknown"/>
		</gml:TimePeriod>
	</sml:validTime>
	<sml:capabilities name="offerings">
		<sml:CapabilityList>
			<sml:capability name="olkad1cl01_offering_1">
				<swe:Text definition="http://www.opengis.net/def/offering/identifier">
					<swe:label>olkad1cl01_offering_1</swe:label>
					<swe:value>http://idena.navarra.es/olk/ad1/cl01/offering/1</swe:value>
				</swe:Text>
			</sml:capability>
		</sml:CapabilityList>
	</sml:capabilities>
	<sml:featuresOfInterest>
		<sml:FeatureList definition="http://www.opengis.net/def/featureOfInterest/identifier">
			<swe:label>featuresOfInterest</swe:label>
			<sml:feature xlink:href="http://idena.navarra.es/olk/ad1"/>
		</sml:FeatureList>
	</sml:featuresOfInterest>
	<sml:inputs>
		<sml:InputList>
			<sml:input name="Chlorine">
				<sml:ObservableProperty definition="http://sweet.jpl.nasa.gov/2.3/matrElementalMolecule.owl#Cl2"/>
			</sml:input>
		</sml:InputList>
	</sml:inputs>
	<sml:outputs>
		<sml:OutputList>
			<sml:output name="Chlorine">
				<swe:Quantity definition="http://sweet.jpl.nasa.gov/2.3/matrElementalMolecule.owl#Cl2">
					<swe:label>Chlorine</swe:label>
					<swe:uom code="mg/L"/>
				</swe:Quantity>
			</sml:output>
		</sml:OutputList>
	</sml:outputs>
	<sml:position>
		<swe:Vector referenceFrame="urn:ogc:def:crs:EPSG::4326">
			<swe:coordinate name="easting">
				<swe:Quantity axisID="x">
					<swe:uom code="degree"/>
					<swe:value>42.843</swe:value>
				</swe:Quantity>
			</swe:coordinate>
			<swe:coordinate name="northing">
				<swe:Quantity axisID="y">
					<swe:uom code="degree"/>
					<swe:value>-1.5804</swe:value>
				</swe:Quantity>
			</swe:coordinate>
		</swe:Vector>
	</sml:position>
</sml:PhysicalComponent>
```

**Comment by CarstenHollmann** [comment]
@jruizaranguren I was not able to reproduce the issue you mentioned but I have added some checks depending on the exception log you have posted.
The changes are in the develop branch. It would be great if you can check if your issue is solved with these changes.

**Comment by CarstenHollmann** [comment]
@dbciar I have implemented the support of `QuantityRange` as a field element of the `DataRecord` in the develop branch.

**Comment by dbciar** [comment]
@CarstenHollmann Thanks, I'll give it a try.

**Comment by jruizaranguren** [comment]
@CarstenHollmann, I have updated our dev environments to the last develop branch commit. It is working now as it allways do after fresh install. If I get again the problem I will reopen the issue. Thanks.
