### ISSUE TITLE
4.3.6: Throws NPE resulting in 500er internal server error if coordinate name is not northing and easting

### ISSUE THREAD

**Issue by EHJ-52n** [52North/SOS#451]
I have the following sensor system position:
```xml
<sml:position name="stationPosition">
<swe:Position fixed="false" referenceFrame="urn:ogc:def:crs:EPSG:4326">
  <swe:location>
    <swe:Vector gml:id="STATION_LOCATION">
      <swe:coordinate name="latitude">
        <swe:Quantity axisID="y">
          <swe:uom code="deg" xlink:href="urn:x-ogc:def:uom:OGC:deg"/>
          <swe:value>51.9348</swe:value>
        </swe:Quantity>
      </swe:coordinate>
      <swe:coordinate name="longitude">
        <swe:Quantity axisID="x">
          <swe:uom code="deg" xlink:href="urn:x-ogc:def:uom:OGC:deg"/>
          <swe:value>7.6524</swe:value>
        </swe:Quantity>
      </swe:coordinate>
      <swe:coordinate name="altitude">
        <swe:Quantity axisID="z">
          <!--200-->
          <swe:uom code="m" xlink:href="urn:x-ogc:def:uom:OGC:m"/>
          <swe:value>200</swe:value>
        </swe:Quantity>
      </swe:coordinate>
    </swe:Vector>
  </swe:location>
</swe:Position>
</sml:position>
```

The problem here with version 4.3.6 is that the expected coordinate names are:
- ```easting```,
- ```northing```, and
- ```altitude```.

Please add the options ```latitude``` and ```longitude``` or improve the error handling in a way, that the user of the service receives some information about the real problem (e.g. tomcat localhost.log and not 52nSOS.log):

```
SEVERE: Servlet.service() for servlet [SOS] in context with path [/52nSOS##4.3.6] threw exception
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:192)
        at com.google.common.base.Joiner.toString(Joiner.java:436)
        at com.google.common.base.Joiner.appendTo(Joiner.java:108)
        at com.google.common.base.Joiner.appendTo(Joiner.java:152)
        at com.google.common.base.Joiner.join(Joiner.java:193)
        at com.google.common.base.Joiner.join(Joiner.java:183)
        at org.n52.sos.converter.CoordianteTransformator.transformSweCoordinates(CoordianteTransformator.java:519)
        at org.n52.sos.converter.CoordianteTransformator.transformPosition(CoordianteTransformator.java:472)
        at org.n52.sos.converter.CoordianteTransformator.checkAbstractProcess(CoordianteTransformator.java:435)
        at org.n52.sos.converter.CoordianteTransformator.checkAbstractSensorML(CoordianteTransformator.java:413)
        at org.n52.sos.converter.CoordianteTransformator.modifyDescribeSensorResponse(CoordianteTransformator.java:390)
        at org.n52.sos.converter.CoordianteTransformator.modifyResponse(CoordianteTransformator.java:196)
        at org.n52.sos.request.operator.AbstractRequestOperator.checkForModifierAndProcess(AbstractRequestOperator.java:232)
        at org.n52.sos.request.operator.AbstractRequestOperator.receiveRequest(AbstractRequestOperator.java:167)
        at org.n52.sos.service.operator.AbstractServiceOperator.receiveRequest(AbstractServiceOperator.java:61)
        at org.n52.sos.binding.PoxBinding.doPostOperation(PoxBinding.java:73)
```

Potential location for a fix: https://github.com/52North/SOS/blob/master/converter/transformation/coordinate/src/main/java/org/n52/sos/converter/CoordianteTransformator.java#L500

**Comment by CarstenHollmann** [comment]
Fixed by commit 6202f76497395d1532fba14e242fc6390a90ec64 in develop version (4.4.0)
