### ISSUE TITLE
Cannot run on Tomcat: ClassLoaderLeakPreventor is a dork.

### ISSUE THREAD

**Issue by mikevdg** [52North/sos#561]
A vanilla build works fine. A build with:

$ mvn -DskipTests=true package -Pconfigure-datasource,oracle

does this when deployed in Tomcat (these are Tomcat's logs, latest Tomcat 8 and Tomcat 9 have the same behaviour):

    ClassLoaderLeakPreventor: Settings for se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventor (CL: 0x36f6f8a8):
    ClassLoaderLeakPreventor:   stopThreads = true
    ClassLoaderLeakPreventor:   stopTimerThreads = true
    ClassLoaderLeakPreventor:   executeShutdownHooks = true
    ClassLoaderLeakPreventor:   threadWaitMs = 5000 ms
    ClassLoaderLeakPreventor:   shutdownHookWaitMs = 10000 ms
    ClassLoaderLeakPreventor: Initializing context by loading some known offenders with system             classloader
    26-Jul-2017 16:37:07.614 SEVERE [localhost-startStop-2]     org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full     details will be found in the appropriate container log file
    26-Jul-2017 16:37:07.614 SEVERE [localhost-startStop-2] org.apache.catalina.core.StandardContext.startInternal Context [/52n-sos-webapp] startup failed due to previous errors
    ClassLoaderLeakPreventor: se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventor shutting down context by removing known leaks (CL: 0x36f6f8a8)
    java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventor.fixGeoToolsLeak(ClassLoaderLeakPreventor.java:1472)
	at se.jiderhamn.classloader.leak.prevention.ClassLoaderLeakPreventor.contextDestroyed(ClassLoaderLeakPreventor.java:677)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4792)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5429)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    ClassLoaderLeakPreventor: Internal registry of java.beans.PropertyEditorManager not found
    ClassLoaderLeakPreventor: Looping 0 RMI Targets to find leaks
    ClassLoaderLeakPreventor: Looping 0 RMI Targets to find leaks
    ClassLoaderLeakPreventor: Stopping Thread 'Thread[WeakCollectionCleaner,8,main]' of type     org.geotools.util.WeakCollectionCleaner running in web app after 5000 ms 
    ClassLoaderLeakPreventor: Custom ThreadLocal of type org.springframework.core.NamedThreadLocal: Prototype beans currently in creation with value null will be remove()d from Thread[localhost-startStop-2,5,main]
    ClassLoaderLeakPreventor: Since Java 1.6+ is used, we can call public static final void java.util.ResourceBundle.clearCache(java.lang.ClassLoader)
    ClassLoaderLeakPreventor: Releasing web app classloader from Apache Commons Logging
    26-Jul-2017 16:37:12.673 INFO [localhost-startStop-2] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/mikevdg/apps/apache-tomcat-8.5.16/webapps/52n-sos-webapp.war] has finished in [9,825] ms

Deployment might have finished, but you get 404s when you try to access the application. Startup failed because of some memory leak catcher stopping it.

My code does have changes in it:

* odjbc version set to 11.2.0.3, because that's what I had.
* In pom.xml, https://repo.boundlessgeo.com/main changed to http because https certificate was broken.
* Significant hibernate mapping changes.
* datasource.properties modified.

None of these should cause the above failure as far as I can tell.

**Comment by CarstenHollmann** [comment]
I guess it's not the ClassLoaderLeakPreventor.

Have you checked the SOS log file?

Because you mentioned `Significant hibernate mapping changes` which probably causes the issue that the SOS is not started. 

Please check the SOS log file.

**Comment by mikevdg** [comment]
Assuming the cause was my own modifications. It has compiled fine since, no changes (?).
