### ISSUE TITLE
Problem with public.series.offeringId column when updating to latest 4.4.0 from 4.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by EHJ-52n** [52North/sos#570]
I have a database using a SOS 4.4.0-SNAPSHOT instance (https://github.com/52North/SOS/commit/0e33c8dd440800d267e6f31af785a31348899b01) and need to update to the latest 4.4.0 release version.

When installing the release over the database with "force updating tables" I get the following error message:
> Error! Could not connect to the database: ERROR: column "offeringid" contains null values. Command: alter table public.series add column offeringId int8 not null

The according log output:
```
2017-10-05 08:36:53,583 ERROR [http-nio-127.0.0.1-8080-exec-19] [AbstractInstallController.java:155] Could not connect to the database: ERROR: column "offeringid" contains null values. Command: alter table public.series add column offeringId int8 not null
org.n52.sos.exception.ConfigurationException: ERROR: column "offeringid" contains null values. Command: alter table public.series add column offeringId int8 not null 
    at org.n52.sos.ds.datasource.AbstractHibernateDatasource.execute(AbstractHibernateDatasource.java:660) ~[AbstractHibernateDatasource.class:na]
    at org.n52.sos.ds.datasource.AbstractHibernateDatasource.execute(AbstractHibernateDatasource.java:532) ~[AbstractHibernateDatasource.class:na]
    at org.n52.sos.web.install.InstallFinishController.process(InstallFinishController.java:121) ~[InstallFinishController.class:na]
    at org.n52.sos.web.install.InstallFinishController.post(InstallFinishController.java:80) ~[InstallFinishController.class:na]
```

How should I adjust the series table to match the requiresment of the v4.4.0? 
What information should be contained in the column offeringid?
Is there any SQL script, I can execute to update the table?

**Comment by EHJ-52n** [comment]
Perform the database updates for v4.3.x to v4.4 available in the `sql` subfolder of the webapp.

I applied:

- `PG_update_43_44.sql`
- `PG_update_43_44_series_table.sql`
